/*!40101 SET NAMES utf8 */;
-- auto generated by yint package builder
-- export date: 2023-04-19 10:03:16
-- please contact iinti_cn(wechat) to get business support

create  database IF NOT EXISTS malenia ;
use malenia;

-- drop table if exist
drop table if exists metric;
drop table if exists metric_tag;
drop table if exists server_node;
drop table if exists sys_config;
drop table if exists sys_log;
drop table if exists user_info;

-- create tables
CREATE TABLE `metric_day`
(
    `id`          bigint      NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `name`        varchar(64) NOT NULL COMMENT '指标名称',
    `time_key`    varchar(64) NOT NULL COMMENT '时间索引',
    `tags_md5`    varchar(64) NOT NULL COMMENT '对于tag字段自然顺序拼接求md5',
    `tag1`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag2`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag3`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag4`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag5`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `type`        varchar(8)  NOT NULL COMMENT '指标类型：（counter、gauge、timer，请注意暂时只支持这三种指标）',
    `value`       double      NOT NULL COMMENT '指标值',
    `create_time` datetime             DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_record` (`name`,`tags_md5`,`time_key`),
    KEY           `idx_query` (`name`,`tags_md5`),
    KEY `idx_delete` (`name`,`create_time`) COMMENT '给删除指标使用'
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4  COMMENT='监控指标,天级';

CREATE TABLE `metric_hour`
(
    `id`          bigint      NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `name`        varchar(64) NOT NULL COMMENT '指标名称',
    `time_key`    varchar(64) NOT NULL COMMENT '时间索引',
    `tags_md5`    varchar(64) NOT NULL COMMENT '对于tag字段自然顺序拼接求md5',
    `tag1`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag2`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag3`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag4`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag5`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `type`        varchar(8)  NOT NULL COMMENT '指标类型：（counter、gauge、timer，请注意暂时只支持这三种指标）',
    `value`       double      NOT NULL COMMENT '指标值',
    `create_time` datetime             DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_record` (`name`,`tags_md5`,`time_key`),
    KEY           `idx_query` (`name`,`tags_md5`),
    KEY `idx_delete` (`name`,`create_time`) COMMENT '给删除指标使用'
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4  COMMENT='监控指标,小时级';

CREATE TABLE `metric_minute`
(
    `id`          bigint      NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `name`        varchar(64) NOT NULL COMMENT '指标名称',
    `time_key`    varchar(64) NOT NULL COMMENT '时间索引',
    `tags_md5`    varchar(64) NOT NULL COMMENT '对于tag字段自然顺序拼接求md5',
    `tag1`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag2`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag3`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag4`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `tag5`        varchar(64)          DEFAULT NULL COMMENT '指标tag',
    `type`        varchar(8)  NOT NULL COMMENT '指标类型：（counter、gauge、timer，请注意暂时只支持这三种指标）',
    `value`       double      NOT NULL COMMENT '指标值',
    `create_time` datetime             DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_record` (`name`,`tags_md5`,`time_key`),
    KEY           `idx_query` (`name`,`tags_md5`),
    KEY `idx_delete` (`name`,`create_time`) COMMENT '给删除指标使用'
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4  COMMENT='监控指标,分钟级';

CREATE TABLE `metric_tag`
(
    `id`        bigint      NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `name`      varchar(64) NOT NULL COMMENT '指标名称',
    `tag1_name` varchar(64) DEFAULT NULL COMMENT '指标tag',
    `tag2_name` varchar(64) DEFAULT NULL COMMENT '指标tag',
    `tag3_name` varchar(64) DEFAULT NULL COMMENT '指标tag',
    `tag4_name` varchar(64) DEFAULT NULL COMMENT '指标tag',
    `tag5_name` varchar(64) DEFAULT NULL COMMENT '指标tag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_record` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4  COMMENT='指标tag定义';


CREATE TABLE `server_node`
(
    `id`               bigint       NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `server_id`        varchar(64)  NOT NULL COMMENT '服务器id，唯一标记服务器',
    `last_active_time` datetime              DEFAULT NULL COMMENT '最后心跳时间',
    `create_time`      datetime              DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `ip`               varchar(512) NOT NULL DEFAULT '',
    `port`             int          NOT NULL COMMENT 'springboot 服务开启端口',
    `enable`           tinyint(1) NOT NULL DEFAULT '1' COMMENT '服务器是否启用',
    `local_ip`         varchar(512)           DEFAULT NULL COMMENT '本地IP',
    `out_ip`           varchar(512)           DEFAULT NULL COMMENT '工作ip',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_record` (`server_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4  COMMENT='服务器节点，多台服务器组成代理集群';

CREATE TABLE `sys_config`
(
    `id`             bigint NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `config_comment` varchar(128)  DEFAULT NULL COMMENT '配置备注',
    `config_key`     varchar(64)   DEFAULT NULL COMMENT 'key',
    `config_value`   varchar(1024) DEFAULT NULL COMMENT 'value',
    `create_time`    datetime      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UNIQUE KEY `uniq_record` (`config_comment` ,`config_key`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4  COMMENT='系统配置';


CREATE TABLE `sys_log`
(
    `id`          bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `username`    varchar(100) DEFAULT NULL COMMENT '操作用户名',
    `operation`   varchar(200) DEFAULT NULL COMMENT '操作',
    `params`      varchar(500) DEFAULT NULL COMMENT ' 操作参数',
    `method_name` varchar(200) DEFAULT NULL COMMENT '操作的方法名',
    `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4  COMMENT='用户访问日志';


CREATE TABLE `user_info`
(
    `id`          bigint   NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `user_name`   varchar(64)       DEFAULT NULL COMMENT '用户名',
    `password`    varchar(64)       DEFAULT NULL COMMENT '密码',
    `last_active` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后登陆时间',
    `create_time` datetime          DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `login_token` varchar(64)       DEFAULT NULL COMMENT '登录token',
    `api_token`   varchar(64)       DEFAULT '' COMMENT 'api 访问token',
    `is_admin`    tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否是管理员',
    `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    `permission` varchar(2048)      DEFAULT '' COMMENT '用户权限',
    `balance`           double(16, 2)       DEFAULT '0.00' COMMENT '账户余额',
    `auth_account`      varchar(64)         DEFAULT NULL COMMENT '代理鉴权账户',
    `auth_pwd`          varchar(64)         DEFAULT NULL COMMENT '代理鉴权密码',
    `actual_pay_amount` double(16, 2)       DEFAULT '0.00' COMMENT '实际支付金额',
    `authentication_real_name` varchar(64) DEFAULT NULL COMMENT '实名认证：真实姓名',
    `authentication_id_card` varchar(64) DEFAULT NULL COMMENT '实名认证：身份证',
    `authentication_company_name` varchar(64) DEFAULT NULL COMMENT '实名认证：企业名称',
    `authentication_license_number` varchar(64) DEFAULT NULL COMMENT '实名认证：营业执照号码',
    `authentication_corporate_name` varchar(64) DEFAULT NULL COMMENT '实名认证：法人姓名',
    `authentication_type` varchar(64) NOT NULL DEFAULT '' COMMENT '实名认证：认证类型,个人,企业',
    `authentication_third_party_id` varchar(64) DEFAULT NULL COMMENT '实名认证：第三方请求id',
    `authentication_comment` varchar(500) DEFAULT NULL COMMENT '实名认证：备注',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4  COMMENT='用户信息';


-- for malenia

CREATE TABLE `access_record`
(
    `id`           bigint(11)  NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `access_user`  varchar(64) NOT NULL COMMENT '对应的账户',
    `target_host`  varchar(128) NOT NULL COMMENT '访问的目标网址',
    `record_time`  varchar(32) NOT NULL COMMENT '结算时间，精确到小时',
    `create_time`  datetime             DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `record_md5`   varchar(64) NOT NULL COMMENT '任务id，用于快速查询',
    `access_count` int(11)     NOT NULL DEFAULT '0' COMMENT '访问次数',
    PRIMARY KEY (`id`),
    UNIQUE KEY `unq_md5` (`record_md5`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='用户访问日志';

CREATE TABLE `access_record_history`
(
    `id`           bigint(11)  NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `access_user`  varchar(64) NOT NULL COMMENT '对应的账户',
    `target_host`  varchar(128) NOT NULL COMMENT '访问的目标网址',
    `record_time`  varchar(32) NOT NULL COMMENT '结算时间，精确到小时',
    `create_time`  datetime             DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `record_md5`   varchar(64) NOT NULL COMMENT '任务id，用于快速查询',
    `access_count` int(11)     NOT NULL DEFAULT '0' COMMENT '访问次数',
    PRIMARY KEY (`id`),
    UNIQUE KEY `unq_md5` (`record_md5`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='用户访问日志备份(存放历史记录)';

CREATE TABLE `asset`
(
    `id`          bigint(11)    NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `path`        varchar(1024) NOT NULL COMMENT '文件名称（带路径）',
    `file_size`   bigint(11)    NOT NULL COMMENT '文件大小，展示的时候使用',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `user`        varchar(64)   NOT NULL COMMENT '所属用户',
    `update_time` datetime DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='资产文件，为用户上传到平台，然后在MITM脚本中引用的资源';

CREATE TABLE `auth_white_ip`
(
    `id`          bigint(11)  NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `white_ip`    varchar(50) DEFAULT NULL COMMENT '出口ip',
    `bind_user`   varchar(64) NOT NULL COMMENT '对应的账户',
    `create_time` datetime    DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `comment`     varchar(64) DEFAULT NULL COMMENT '备注',
    `from_api`    tinyint(1)  DEFAULT '0' COMMENT '是否来自API配置',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='出口ip白名单';

CREATE TABLE `bill`
(
    `id`             bigint(11)  NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `product_name`   varchar(64)   DEFAULT NULL COMMENT '产品名称',
    `product_id`     varchar(64)   DEFAULT NULL COMMENT '产品ID',
    `purchase_user`  varchar(64) NOT NULL COMMENT '订购用户',
    `balance_method` tinyint(8)    DEFAULT '1' COMMENT '结算方案',
    `balance_price`  double(16, 2) DEFAULT NULL COMMENT '实际结算价格',
    `bill_time`      varchar(32) NOT NULL COMMENT '结算时间，精确到小时',
    `consume_amount` double(16, 2) DEFAULT NULL COMMENT '消费的金额',
    `create_time`    datetime      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `op_node`        varchar(64)   DEFAULT NULL COMMENT '扣费服务器节点',
    `user_balance`   double(16, 2) DEFAULT NULL COMMENT '当前账户余额',
    PRIMARY KEY (`id`),
    UNIQUE KEY `bill_id` (`product_id`, `purchase_user`, `bill_time`),
    KEY `create_time` (`create_time`),
    KEY `purchase_user` (`purchase_user`),
    KEY `product_id` (`product_id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='对账单，记录各个用户和产品的使用详情，按小时为维度进行统计';

CREATE TABLE `ip_source`
(
    `id`                    bigint(11)  NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `source_key`            varchar(64)          DEFAULT NULL COMMENT '资源key',
    `create_time`           datetime             DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `load_resource_handler` text COMMENT '资源解析处理器',
    `load_url`              varchar(256)         DEFAULT NULL COMMENT '资源下载url',
    `auth_user_name_exp`    varchar(256)         DEFAULT '${upstream_user_name}' COMMENT '鉴权账户表达式',
    `enabled`               tinyint(1)           DEFAULT '1' COMMENT '当前资源是否生效',
    `up_user_name`          varchar(64)          DEFAULT NULL COMMENT '上游代理鉴权账户（解析结果没有是的默认兜底）',
    `up_user_password`      varchar(64)          DEFAULT NULL COMMENT '上游代理鉴权密码',
    `description`           mediumtext COMMENT '本ip池描述',
    `pool_size`             int(4)      NOT NULL DEFAULT '0' COMMENT '预估ip池大小',
    `need_test`             tinyint(1)  NOT NULL DEFAULT '1' COMMENT '是否需要探测可用性',
    `reload_interval`       int(3)      NOT NULL DEFAULT '60' COMMENT 'ip下载时间间隔（秒）',
    `max_alive`             int(3)      NOT NULL DEFAULT '1200' COMMENT '最长存活时间（秒）',
    `support_protocol`      varchar(48) NOT NULL DEFAULT 'HTTP,HTTPS,SOCKS5' COMMENT '本ip池支持的协议',
    `conn_idle_seconds`     int(11)     NOT NULL DEFAULT '5' COMMENT '连接池连接空转时间（秒），超时被系统回收',
    `make_conn_interval`    int(11)     NOT NULL DEFAULT '500' COMMENT '链接缓存池检查和创建时间间隔，单位：秒',
    PRIMARY KEY (`id`),
    UNIQUE KEY `source_id_UNIQUE` (`source_key`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='代理资源池';


CREATE TABLE `mitm_script`
(
    `id`          bigint(11)  NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `user`        varchar(64) NOT NULL COMMENT '所属用户',
    `name`        varchar(64) NOT NULL COMMENT '脚本名称（必须传）',
    `content`     text COMMENT '脚本内容',
    `priority`    tinyint(4) DEFAULT '0' COMMENT '优先级，数字越小优先级越高',
    `enabled`     tinyint(1) DEFAULT '1' COMMENT '当前是否生效',
    `create_time` datetime   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime   DEFAULT NULL COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `script_id_UNIQUE` (`user`, `name`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='MTIM脚本，给用户做逻辑扩展';

CREATE TABLE `order_rate_bill`
(
    `id`          bigint(11)  NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `order_id`    bigint(11) DEFAULT NULL COMMENT '订单ID',
    `time_key`    varchar(64) NOT NULL COMMENT '对账时间，精确到分钟',
    `create_time` datetime   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `rate_usage`  bigint(20) DEFAULT '0' COMMENT '带宽用量',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_key_id_time` (`order_id`, `time_key`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='订单带宽用量流水';


CREATE TABLE `product`
(
    `id`                 bigint(11)  NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `product_id`         varchar(64)   DEFAULT NULL COMMENT '产品ID',
    `product_name`       varchar(64)   DEFAULT NULL COMMENT '产品名称',
    `create_time`        datetime      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `mapping_port_space` varchar(32) NOT NULL COMMENT '该产品映射的端口范围',
    `support_tag`        varchar(256)  DEFAULT NULL COMMENT '产品的标签表达式,规定和约束了下游选择资源的算法,规定了资源类型mapping顺序',
    `enabled`            tinyint(1)    DEFAULT '1' COMMENT '当前产品是否生效',
    `private_product`    tinyint(1)    DEFAULT '0' COMMENT '是否是私有ip',
    `hour_price`         double(6, 2)  DEFAULT NULL COMMENT '使用价格，按小时付费',
    `flow_price`         double(6, 2)  DEFAULT NULL COMMENT '使用价格，按流量付费(G)',
    `description`        mediumtext comment '产品描述',
    `features`           varchar(200)  DEFAULT NULL comment '产品特征标签，可以在前端被快速筛选',
    `tuning_param`       varchar(1024) DEFAULT NULL COMMENT '隧道路由参数(需要上游支持)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `product_id_UNIQUE` (`product_id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='代理产品';

CREATE TABLE `product_source`
(
    `id`          bigint(11) NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `product_id`  varchar(64)         DEFAULT 'plain' COMMENT '产品id',
    `source_key`  varchar(64)         DEFAULT NULL COMMENT '资源名称',
    `create_time` datetime            DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `ratio`       tinyint(4) NOT NULL DEFAULT '1' COMMENT '流量比例',
    PRIMARY KEY (`id`),
    UNIQUE KEY `source_binding_UNIQUE` (`source_key`, `product_id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='资源产品绑定关系';


CREATE TABLE `recharge_record`
(
    `id`                      bigint(11) NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `operator`                varchar(64)   DEFAULT NULL COMMENT '操作人',
    `user`                    varchar(64)   DEFAULT NULL COMMENT '充值目标用户',
    `create_time`             datetime      DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `comment`                 varchar(500)  DEFAULT NULL COMMENT '充值备注',
    `recharge_amount`         double(16, 2) DEFAULT '0.00' COMMENT '充值金额',
    `actual_pay_amount`       double(16, 2) DEFAULT NULL COMMENT '实际支付金额',
    `remain_balance`          double(16, 2) DEFAULT '0.00' COMMENT '充值前余额',
    `total_actual_pay_amount` double(16, 2) DEFAULT NULL COMMENT '充值前实际支付总额',
    `trade_no` varchar(64) DEFAULT NULL COMMENT '支付流水号，支付宝|微信返回',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_trade_no` (`trade_no`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='充值记录表';


CREATE TABLE `user_order`
(
    `id`                      bigint(11)  NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `product_name`            varchar(64)          DEFAULT NULL COMMENT '产品名称',
    `product_id`              varchar(64)          DEFAULT NULL COMMENT '产品ID',
    `purchase_user`           varchar(64) NOT NULL COMMENT '订购用户',
    `create_time`             datetime             DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `balance_method`          tinyint(8)           DEFAULT '1' COMMENT '结算方案',
    `enabled`                 tinyint(1)           DEFAULT '1' COMMENT '是否启用',
    `balance_price`           double(6, 2)         DEFAULT NULL COMMENT '实际结算价格',
    `bandwidth_balance_price` double(6, 2)         DEFAULT NULL COMMENT '带宽实际结算价格备份(避免计费方式切换导致带宽价格丢失),因为修改带宽会对应修改带宽的价格',
    `referer`                 varchar(50)          DEFAULT NULL COMMENT '推荐人',
    `bandwidth_limit`         double(16, 2)        DEFAULT '3.00' COMMENT '带宽限制',
    `random_turning`          tinyint(1)  NOT NULL DEFAULT '0' COMMENT '随机隧道，开启后用户每个请求都会随机',
    `connect_timeout`         int(11)     NOT NULL DEFAULT '5000' COMMENT '连接创建超时时间，超时将会由代理服务器主动502',
    `max_failover_count`      tinyint(4)  NOT NULL DEFAULT '3' COMMENT '最大重试次数',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq` (`product_id`,`purchase_user`) COMMENT '唯一约束'
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='产品订购关系表';

CREATE TABLE `user_order_current_bandwidth`
(
    `id`                bigint        NOT NULL AUTO_INCREMENT COMMENT '自增主建',
    `user_order_id`     bigint        NOT NULL COMMENT '订单ID',
    `server_id`         varchar(64)   NOT NULL COMMENT '当前服务器节点ID',
    `current_bandwidth` double(16, 2) NOT NULL COMMENT '当前服务器、当前订单的带宽情况',
    `last_update_time`  datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改更新时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 0
  DEFAULT CHARSET = utf8mb4 COMMENT ='订单带宽trace表，用于计算多个分布式节点的代理流量带宽';

SET NAMES 'utf8mb4';
-- 以下为初始化样例数据语句

-- 创建一个默认的代理源
INSERT INTO `ip_source` (`id`, `source_key`, `create_time`, `load_resource_handler`, `load_url`, `auth_user_name_exp`,
                         `enabled`, `up_user_name`, `up_user_password`, `description`,
                         `pool_size`, `need_test`, `reload_interval`, `max_alive`, `support_protocol`,
                         `conn_idle_seconds`, `make_conn_interval`)
VALUES (1, 'embed_proxy', '2022-05-16 00:00:00', 'PortSpace', 'localhost:38100-38110', null, 1, null, null,
        '内置测试代理服务,给用户初始化配置调试使用', 10, 1, 240, 300,
        'HTTP,HTTPS,SOCKS5', 20, 300);

-- 使用样例代理源创建一个样例的代理产品服务
INSERT INTO `product` (`id`, `product_name`, `product_id`, `create_time`, `mapping_port_space`, `support_tag`,
                       `enabled`, `hour_price`, `flow_price`, `description`, `features`, `tuning_param`)
VALUES (1, '本机代理', '34f13bcd-e9c6-4acd-b786-e78518965fef', '2022-05-16 19:25:19', '9090-9095', NULL, 1, 1.00, 1.00,
        '使用内置的代理服务器作为上游代理', '本机', '{\"items\":[]}');

-- 关联代理产品和代理源
INSERT INTO `product_source` (`id`, `product_id`, `source_key`, `create_time`, `ratio`)
VALUES (1, '34f13bcd-e9c6-4acd-b786-e78518965fef', 'embed_proxy', '2022-05-16 19:25:27', 1);
